In [1]:
import numpy as np

In [5]:
a = np.arange(20).reshape(5, 4)

In [6]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [7]:
a.shape

(5, 4)

In [8]:
a.ndim

2

In [9]:
a.dtype.name

'int32'

In [10]:
a.itemsize

4

In [11]:
a.size

20

In [12]:
type(a)

numpy.ndarray

In [15]:
b = np.array([10, 12, 16])

In [16]:
b

array([10, 12, 16])

In [17]:
type(b)

numpy.ndarray

In [18]:
np.zeros((2, 8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
np.ones( (10,13,24), dtype=np.int16 )

array([[[1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        ...,
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1]],

       [[1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        ...,
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1]],

       [[1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        ...,
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1]],

       ...,

       [[1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        ...,
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1]],

       [[1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        ...,
        [1, 1, 1, ..., 

In [20]:
np.empty( (27,38) )

array([[8.59943738e-312, 8.59943944e-312, 0.00000000e+000, ...,
        2.97079411e-313, 8.59949168e-312, 4.94065646e-324],
       [8.59943787e-312, 2.12199579e-313, 3.60739284e-313, ...,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       ...,
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [28]:
np.arange( 1, 4, 2 )

array([1, 3])

In [27]:
np.arange( 1, 5, 0.3 )

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8, 3.1, 3.4, 3.7, 4. , 4.3, 4.6,
       4.9])

In [29]:
np.linspace( 2, 22, 9 )

array([ 2. ,  4.5,  7. ,  9.5, 12. , 14.5, 17. , 19.5, 22. ])

In [31]:
x = np.linspace( 0, 2*3.14, 20 )

In [32]:
f = np.sin(x)

In [33]:
a = np.arange(12)

In [34]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [36]:
b = np.arange(10).reshape(2,5)

In [37]:
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [38]:
c = np.arange(24).reshape(2,3,4)

In [39]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [40]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [41]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [42]:
a = np.array( [20,30,40,50] )

In [43]:
b = np.arange( 4 )

In [44]:
b

array([0, 1, 2, 3])

In [45]:
c = a-b

In [46]:
c

array([20, 29, 38, 47])

In [47]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [48]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [49]:
a<35

array([ True,  True, False, False])

In [50]:
A = np.array( [[1,1],
...                [0,1]] )

In [51]:
B = np.array( [[2,0],
...                [3,4]] )

In [52]:
A * B

array([[2, 0],
       [0, 4]])

In [53]:
A @ B

array([[5, 4],
       [3, 4]])

In [54]:
A.dot(B)

array([[5, 4],
       [3, 4]])